<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-israelcolmeneros/blob/main/actividades_ibm_modulo_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Python for Data Science**
Jesus Israel Colmeneros Castañeda
A01361766

# Module 5 - Working with Numpy Arrays & Simple APIs

-Numpy 1D Arrays, es similar a una lista, podemos acceder a la informacion con Idex, podemos usar el metodo dtype para poder saber si es una array, se pueden modificar los elementos de los arra con los index, podemos hacer slicers del array.




-Vector addition and subtraction, es mejor usar vectores y no arrays cuando se pueda porque ocupa menos espacio, los vectores se pueden multiplicar por un escalar, 

-Hay funciones universales como max(), que puede identificar el elmento mas grande en un array.


-linspace, podemos usarlo para generar arrays indicando los parametros dentro de la funcion.

In [1]:
import numpy as np
a=[1,2,3,4,5]
x = np.array(a)
type(x)
x.shape
x.dtype
x.mean()

3.0

In [2]:
np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [3]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [4]:
# Create a python list

a = ["0", 1, "two", "3", 4]

In [5]:
# import numpy library

import numpy as np 
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [6]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [10]:
c = np.array([20, 1, 2, 3, 4])
c
c[4] = 0
c
d = c[1:4]
d

array([1, 2, 3])

In [15]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

# Enter your code here
arr3 = np.subtract(arr1, arr2)
arr3

array([-10,  -1,   8,  17,  26,  35])

In [17]:
# Create a numpy array

x = np.array([1, 2])
x
y = np.array([2, 1])
y
z = np.multiply(x, y)
z

array([2, 2])

In [18]:
a = np.array([10, 20, 30])
a
b = np.array([2, 10, 5])
b
c = np.divide(a, b)
c

array([5., 2., 6.])

In [19]:
X = np.array([1, 2])
Y = np.array([3, 2])
# Calculate the dot product

np.dot(X, Y)

7

In [20]:
# Makeup a numpy array within [-2, 2] and 5 elements

np.linspace(-2, 2, num=5)

array([-2., -1.,  0.,  1.,  2.])

-Numpy 2D Arrays, se pueden crear arrays de mas de una dimension, shape regresara un truple, tambien se pueden usar index para llamar numeros dentro del array, tambien se puede agregar valores como en los arrays o lists.

In [28]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])
type(A)
A.shape
A.dtype
A[1]

A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

C = A * B
print(C)

Z = np.dot(A,B)
print(Z)

[[11  0]
 [ 0 22]]
[[11 12]
 [21 22]]


In [30]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

-Simple APIs, Pandas = API, REST APIs similar a API pero se conecta directo a internet, hay una llamada nba_api que contiene la informacion mas actualizada de NBA.

las APIs tambien se pueden usar para usar modelos de IA, las keys son los accesos al API, se te puede cobrar por cada uso, por ejemplo watson, 

Examen Final

In [32]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [34]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [35]:
A='1234567'
A[1::2]

'246'

In [36]:
Name="Michael Jackson" 
Name.find('el')

5

In [37]:
 '1,2,3,4'.split(',')

['1', '2', '3', '4']

In [39]:
A=['1','2','3']

for a in A:
  print(2*a)

11
22
33


In [40]:
class Points(object):

  def __init__(self,x,y):

    self.x=x

    self.y=y

  def print_point(self):

    print('x=',self.x,'y=',self.y)